<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251231221555 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Génération des tables nécessaires au projet. Le status est défini dans une Enum.';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE app.entrypoint (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, total_portfolio NUMERIC(10, 2) NOT NULL, entrypoint NUMERIC(10, 2) NOT NULL, position_size NUMERIC(10, 2) NOT NULL, status VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_2715DD63A76ED395 ON app.entrypoint (user_id)');
        $this->addSql('CREATE TABLE app.position (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, rank INT NOT NULL, buy_price NUMERIC(10, 2) NOT NULL, target_price NUMERIC(10, 2) NOT NULL, status VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, entrypoint_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_A97453CE98868048 ON app.position (entrypoint_id)');
        $this->addSql('CREATE TABLE "app"."user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, upper_range NUMERIC(10, 2) DEFAULT NULL, buy_limit NUMERIC(10, 2) DEFAULT NULL, last_cac_updated_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_4C0F3A965D69E1F5 ON "app"."user" (last_cac_updated_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "app"."user" (email)');
        $this->addSql('ALTER TABLE app.entrypoint ADD CONSTRAINT FK_2715DD63A76ED395 FOREIGN KEY (user_id) REFERENCES "app"."user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE app.position ADD CONSTRAINT FK_A97453CE98868048 FOREIGN KEY (entrypoint_id) REFERENCES app.entrypoint (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "app"."user" ADD CONSTRAINT FK_4C0F3A965D69E1F5 FOREIGN KEY (last_cac_updated_id) REFERENCES market_data.cac_daily (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE app.entrypoint DROP CONSTRAINT FK_2715DD63A76ED395');
        $this->addSql('ALTER TABLE app.position DROP CONSTRAINT FK_A97453CE98868048');
        $this->addSql('ALTER TABLE "app"."user" DROP CONSTRAINT FK_4C0F3A965D69E1F5');
        $this->addSql('DROP TABLE app.entrypoint');
        $this->addSql('DROP TABLE app.position');
        $this->addSql('DROP TABLE "app"."user"');
    }
}
