<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260116220341 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE entrypoint (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, entrypoint NUMERIC(10, 2) NOT NULL, status VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_4EA2FB2CA76ED395 ON entrypoint (user_id)');
        $this->addSql('CREATE TABLE position (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, rank INT NOT NULL, buy_price NUMERIC(10, 2) NOT NULL, target_price NUMERIC(10, 2) NOT NULL, lvc_buy_price NUMERIC(10, 2) DEFAULT NULL, lvc_target_price NUMERIC(10, 2) DEFAULT NULL, status VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, entrypoint_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_462CE4F598868048 ON position (entrypoint_id)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, total_portfolio NUMERIC(10, 2) DEFAULT NULL, spread INT DEFAULT 2 NOT NULL, position_size NUMERIC(10, 2) DEFAULT NULL, last_cac_updated_id INT DEFAULT NULL, upper_range NUMERIC(10, 2) DEFAULT NULL, buy_limit NUMERIC(10, 2) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (email)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0 ON messenger_messages (queue_name)');
        $this->addSql('CREATE INDEX IDX_75EA56E0E3BD61CE ON messenger_messages (available_at)');
        $this->addSql('CREATE INDEX IDX_75EA56E016BA31DB ON messenger_messages (delivered_at)');
        $this->addSql('ALTER TABLE entrypoint ADD CONSTRAINT FK_4EA2FB2CA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE position ADD CONSTRAINT FK_462CE4F598868048 FOREIGN KEY (entrypoint_id) REFERENCES entrypoint (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA market_data');
        $this->addSql('ALTER TABLE entrypoint DROP CONSTRAINT FK_4EA2FB2CA76ED395');
        $this->addSql('ALTER TABLE position DROP CONSTRAINT FK_462CE4F598868048');
        $this->addSql('DROP TABLE entrypoint');
        $this->addSql('DROP TABLE position');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
